title: WARRIORS Baseball Academy
author: Cody Box
description: Awesome place for people peopl epople to come and support us!

# social links
twitter_username: "@warriorsbb"
github_username:  "@baksterbox"

show_excerpts: true 

theme: jekyll-theme-slate
